#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Ricardo Zacarias Personal Webpage'
  rel-author: 'Ricardo Zacarias'
  rel-publisher: ''

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-164344589-1'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # Ricardo Zacarias

  A neuroscientist inspired by building stories from numbers.	

contact: >
  # Contact

  You may contact me [through my email](mailto:ricardo.zsilva@gmail.com) or [LinkedIn](https://www.linkedin.com/in/ricardo-zacarias/) if you have any questions.

#-------------------------------
# Work Section

projects:
- {name: 'Project One', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Project Two', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'github', link: 'https://github.com/ricardozacarias'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/ricardo-zacarias/'}
- {icon: 'envelope', link: 'mailto:ricardo.zsilva@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
